const object = [
    {
        image : "../images/p1.jpg",
        brand: "Levi's",
        aboutCloths:"Men's Skinny Jeans",
        type:"pant",
        price:254,
        ActualPrice:299,
        off:"15",
        id:1,
        totalquantity:19,
    },
    {
        image : "../images/p2.jpg",
        brand: "Killer's",
        aboutCloths:"Men's Fit Jeans",
        type:"pant",
        price:200,
        ActualPrice:250,
        off:"10",
        id:2,
        totalquantity:19,
    },
    {
        image : "../images/p3.jpg",
        brand: "spyker",
        aboutCloths:"Men's Jeans",
        type:"pant",
        price:150,
        ActualPrice:200,
        off:"8",
        id:3,
        totalquantity:19,

    },
    {
        image : "../images/shirt1.jpg",
        brand: "Levi's",
        aboutCloths:"Men's Shirt",
        type:"shirt",
        price:150,
        ActualPrice:299,
        off:"12",
        id:4,
        totalquantity:19,
    },
    {
        image : "../images/s2.jpg",
        brand: "Puma's",
        aboutCloths:"Men's Fit Shirt",
        type:"shirt",
        price:149,
        ActualPrice:199,
        off:"17",
        id:5,
        totalquantity:19,
    },
]
export default object;